### PR TITLE
Support Puppet v4

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
This requires stdlib 4.6.0, though it is compatible with your setup.

https://github.com/puppetlabs/puppetlabs-stdlib#version-compatibility

**Comment by ghoneycutt** [comment]
@jwennerberg woohoo! Got the Puppet v4 compatibility going

**Comment by Phil-Friderici** [comment]
Thanks @ghoneycutt
again, +1 from my side

**Comment by jwennerberg** [comment]
Thanks! Released in 1.1.0

**Pull request merged**
