### PR TITLE
Change default behavior for cron.allow/cron.deny files

### PR DESCRIPTION
**Pull request by jwennerberg**

### CODE REVIEW

**Comment by jwennerberg** [comment]
@Phil-Friderici do you have time to have a look at this?

**Comment by Phil-Friderici** [comment]
@jwennerberg looks good me +1
We are'nt using this module here, so I am sorry can't help with a real life test.

**Comment by xanddah** [comment]
Yes, it should work. Haven't had time to test it on the cron-servers, though.

**Comment by ghoneycutt** [comment]
@jwennerberg since this changes default behavior it should be released as 2.0.0. It is worth taking a look and seeing if there are any other breaking changes that are desired and do them all in that release.

**Comment by jwennerberg** [comment]
I will merge this. Some more minor updates will follow before making a new release.

**Pull request merged**
