### PR TITLE
Manage file attributes for cron files and directories

### PR DESCRIPTION
**Pull request by jwennerberg**

### CODE REVIEW

**Comment by jwennerberg** [comment]
@Phil-Friderici care to take a look?

**Comment by Phil-Friderici** [comment]
The code looks good. I would only recommend to add validation for the parameters just to make sure.
If you have a use case to be able to modify owner,group and mode for these directories it will work.

Maybe it would be good enough to only use one parameter for owner,group & mode and use that for all cases ?

**Comment by jwennerberg** [comment]
There's a use case for this. In order to pass CIS benchmarks the permissions of system cron files must be tweaked.

Since this module is otherwise quite small I don't see the extra 100 lines or so as a big problem.

**Comment by Phil-Friderici** [comment]
should I add parameter validation to it ?

**Comment by jwennerberg** [comment]
@Phil-Friderici I rebased this and did some cleanup. what do you think? does it make sense to validate owner/group/mode attributes?

**Comment by Phil-Friderici** [comment]
In my eyes validation is always a good thing. It enhance comfort and security.
Mode could be validated nicely with RegEx to contains exactly four numbers.
For owner/group you could only validate that it's a string to prevent using wrong types.

**Comment by Phil-Friderici** [comment]
The validation should have corresponding spec tests.

**Comment by jwennerberg** [comment]
It's not quite that easy. mode can be both numeric and symbolic (e.g. a=r,ug+w). owner and group can be either a name or an ID.

**Comment by Phil-Friderici** [comment]
...only if you want to support non numerical here...
Do you think there might be a chance that these more flexible modes could be used for the cron directories ?

**Comment by jwennerberg** [comment]
Since we pass this straight to the resource declaration I don't think it's nice to limit the functionality of puppet just because of a test.

If we really want full validation, we should do it properly.

**Comment by Phil-Friderici** [comment]
pragmatic vs academic, choose your poison ;)

**Comment by ghoneycutt** [comment]
modes should never be symbolic, they should always be four digital octal notation. user/groups can be verified with is_string() which will also pick up numbers since those are treated as strings.

**Comment by jwennerberg** [comment]
Not sure I agree.. but I can't spend more time on this. I've added validation for the owner, group and mode parameters.

**Comment by Phil-Friderici** [comment]
Code & spec tests looks complete to me. Can't test it in real life as we don't use it up to now. Could arrange some testing if nobody else can test it otherwise.
@jwennerberg Please let me know.

**Comment by ghoneycutt** [comment]
@jwennerberg if it is any consolation

"You should use numeric notation whenever possible."

http://docs.puppetlabs.com/guides/style_guide.html#file-modes

**Comment by Phil-Friderici** [comment]
@nbentoumi could you please test this change ?

**Comment by Phil-Friderici** [comment]
@jwennerberg code looks good. Only tests for path validations are missing.

**Comment by Phil-Friderici** [comment]
oh, and README should be updated too

**Comment by Phil-Friderici** [comment]
@jwennerberg I have rebased this code against master and added the specs and docu in https://github.com/Ericsson/puppet-module-cron/pull/19

**Comment by jwennerberg** [comment]
Replaced by PR #20

**Pull request closed without merging**
