### PR TITLE
Manage file attributes for cron files and directories (remastered)

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Successor of PR https://github.com/Ericsson/puppet-module-cron/pull/6

Rebased against updated master branch.
Add spec tests for path validations
Add documentation for new parameters to README.md

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@jwennerberg please have a look

**Comment by jwennerberg** [comment]
Looks good @Phil-Friderici , thanks!

My commits should be squashed though. Will you take care of that in this PR or do you want me to fix it?

**Comment by Phil-Friderici** [comment]
@jwennerberg have squashed your commits into one (https://github.com/Phil-Friderici/puppet-module-cron/commit/37c4f0f0437f0fbf08a3ec02a378512f672a57bc).

Think the other commits are included because they have been commited in the time between.

**Comment by jwennerberg** [comment]
@Phil-Friderici please have a look at PR #20 instead

**Comment by Phil-Friderici** [comment]
closed in favour of https://github.com/Ericsson/puppet-module-cron/pull/20

**Pull request closed without merging**
