### PR TITLE
(GH-52) Add support for EL7

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Solves #52

**Comment by ghoneycutt** [comment]
@Phil-Friderici This has not been functionally tested on an EL7 and should be before merged.

**Comment by Phil-Friderici** [comment]
I bet it will work, any chance to let it run on a EL7 system ?

**Comment by ghoneycutt** [comment]
@Phil-Friderici I don't have a system readily available as my current client is not using this module. Perhaps our Swedish friends have a system?

**Comment by nalyanyam** [comment]
@ghoneycutt , @Phil-Friderici 
I have tested this update on RHEL 7.5 and worked well.

**Comment by ghoneycutt** [comment]
+1

**Comment by Phil-Friderici** [comment]
closing & re-opening to trigger a Travis run only

**Comment by Phil-Friderici** [comment]
Thanks for your work gentleman ! Released in 2.4.0 :)

**Comment by ghoneycutt** [comment]
Thanks @Phil-Friderici

**Pull request merged**
